{
 "title": "Jenkins Sentinel",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "SELECT DISTINCT pipeline_name FROM builds ORDER BY pipeline_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Build Duration",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select pipeline_name, build_number, status, total_duration from builds WHERE pipeline_name = '$pipeline' AND $__timeFilter(build_start_time);"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS failed_total\nFROM   builds\nWHERE  pipeline_name = '$pipeline'\n  AND  status = 'failure'\n  AND $__timeFilter(build_start_time);"
    }
   ]
  },
  {
   "title": "Successful builds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS success_total\nFROM   builds\nWHERE  pipeline_name = '$pipeline'\n  AND  status = 'success'\n  AND $__timeFilter(build_start_time);"
    }
   ]
  },
  {
   "title": "Success Percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND(\n    100.0 * SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END)\n    / NULLIF(COUNT(*), 0),\n    1\n  ) AS success_pct\nFROM builds\nWHERE pipeline_name = '$pipeline'\n  AND $__timeFilter(build_start_time);"
    }
   ]
  },
  {
   "title": "Average Build Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(AVG(total_duration)::numeric, 2) as avg_duration_seconds\nFROM builds\nWHERE total_duration > 0 AND pipeline_name='$pipeline'\n  AND $__timeFilter(build_start_time)"
    }
   ]
  },
  {
   "title": "Duration Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT duration_range, count\nFROM (\n    SELECT \n        CASE \n            WHEN total_duration <= 60 THEN '0-1min'\n            WHEN total_duration <= 120 THEN '1-2min'\n            WHEN total_duration <= 240 THEN '2-4min'\n            WHEN total_duration <= 480 THEN '4-8min'\n            WHEN total_duration <= 960 THEN '8-16min'\n            WHEN total_duration <= 1920 THEN '16-32min'\n            WHEN total_duration <= 3840 THEN '32-64min'\n            WHEN total_duration <= 7680 THEN '64-128min'\n            WHEN total_duration <= 10800 THEN '128-180min'\n            ELSE '180min+'\n        END AS duration_range,\n        COUNT(*) AS count\n    FROM builds\n    WHERE pipeline_name = '$pipeline'\n      AND total_duration IS NOT NULL\n      AND build_start_time IS NOT NULL\n      AND $__timeFilter(build_start_time)\n    GROUP BY \n        CASE \n            WHEN total_duration <= 60 THEN '0-1min'\n            WHEN total_duration <= 120 THEN '1-2min'\n            WHEN total_duration <= 240 THEN '2-4min'\n            WHEN total_duration <= 480 THEN '4-8min'\n            WHEN total_duration <= 960 THEN '8-16min'\n            WHEN total_duration <= 1920 THEN '16-32min'\n            WHEN total_duration <= 3840 THEN '32-64min'\n            WHEN total_duration <= 7680 THEN '64-128min'\n            WHEN total_duration <= 10800 THEN '128-180min'\n            ELSE '180min+'\n        END\n) AS duration_dist\nORDER BY \n    CASE duration_range\n        WHEN '0-1min' THEN 1\n        WHEN '1-2min' THEN 2\n        WHEN '2-4min' THEN 3\n        WHEN '4-8min' THEN 4\n        WHEN '8-16min' THEN 5\n        WHEN '16-32min' THEN 6\n        WHEN '32-64min' THEN 7\n        WHEN '64-128min' THEN 8\n        WHEN '128-180min' THEN 9\n        WHEN '180min+' THEN 10\n    END;"
    }
   ]
  }
 ]
}