# example package.toml
[user]
name = "username"

[repo]
[repo.prefix]
utilities = 'sudo apt install' 
dev       = 'sudo apt install' 
# external  = true 
# python    = 'pip3 install' 
# rust      = 'cargo install' 
# npm       = 'npm install'
# vscode    = 'code --install-extension'

[repo.utilities] 
download       = ["curl", "aria2", "wget"]
pdf            = ["zathura", "evince"]
misc           = [
	"software-properties-common",
	"apt-transport-https",
	"feh", 
	"rsync", 
]

# external script that need to be run
[repo.external]
onlyoffice = true
brave      = true
vscode     = true


[repo.dev]
vim       = "vim"
git       = "git"
cpp       = ["g++", "cmake", "clang-format"]
front-end = ["node", "npm"]

# installation using pip
[repo.python]
ipython3   = "ipython3"
glances    = "glances"

# installation using cargo
[repo.rust]
ripgrep  = "ripgrep"
exa      = "exa"

# examples
[repo.npm]
npm = ["create-react-app", "commander"]


# code --install-extension
[repo.vscode]
extensions = [
	"bungcip.better-toml",
	"DavidAnson.vscode-markdownlint",
	"msjsdiag.debugger-for-chrome",
	"yzhang.markdown-all-in-one"
]

[dotfile]
[dotfile.home]
files = [
	".vimrc",
	".bashrc"
]
