[os-packages] 
dependent = 'apt-get'
command = 'sudo apt install -y'
packages = [
	"curl", 
	"aria2", 
	"software-properties-common",
	"apt-transport-https",
	"feh", 
	"python3-pip"
]

[python]
dependent = 'pip3'
command = 'pip3 install'
packages= [
	"pandas", 
	"numpy", 
	"requests"
] 

[cargo]
dependent = 'cargo'
command = 'cargo install'
utilities = ["ripgrep", "exa"]

[npm]
dependent = 'npm'
command = 'npm install'
npm = ["create-react-app", "commander"]


[vscode]
dependent = 'code'
command = 'code --install-extension'
extensions = [
	"bungcip.better-toml",
	"DavidAnson.vscode-markdownlint",
	"msjsdiag.debugger-for-chrome",
	"yzhang.markdown-all-in-one"
]

