[repo]
# commented ones are not picked up for installation
# prefix used when installing programs from the repo
[prefix]
os_packages = ['apt-get', 'sudo apt install -y']
python    = ['pip3', 'pip3 install']
rust      = ['cargo', 'cargo install' ]
npm       = ['npm', 'npm install']
vscode    = ['code' 'code --install-extension']

[os-packages] 
utilities = [
	"curl", 
	"aria2", 
	"wget",
	"zathura",
	"evince",
	"software-properties-common",
	"apt-transport-https",
	"feh", 
	"rsync"
]
development_tools = [
	"vim",
	"git",
	"g++", 
	"cmake", 
	"clang-format",
	"node",
	"npm"
]

[python-packages]
libs = ["pandas", "numpy", "requests"] 
utilities = ["glances", "ranger-fm"]

[cargo]
utilities = ["ripgrep", "exa"]

[npm]
npm = ["create-react-app", "commander"]


[repo.vscode]
extensions = [
	"bungcip.better-toml",
	"DavidAnson.vscode-markdownlint",
	"msjsdiag.debugger-for-chrome",
	"yzhang.markdown-all-in-one"
]

