[package]
name = "color-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
