{
 "title": "Jenkins Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_pipeline_run_completed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ci_pipeline_run_success_total / ci_pipeline_run_completed_total)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CI Build Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"jenkins\" && name=\"BUILD ecgo-docker-pipeline\"} \n| select(\n    span.ci.pipeline.run.number,\n    span.ci.pipeline.run.result\n)",
     "spss": 5,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Jenins Executor Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jenkins_executor_busy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}