version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: jenkins_data
      POSTGRES_USER: jenkins
      POSTGRES_PASSWORD: jenkins123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - jenkins-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
    networks:
      - jenkins-network

volumes:
  postgres_data:
  grafana_data:

networks:
  jenkins-network:
    driver: bridge
