jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: jenkins
          password: "#jbcrypt:$2a$10$6jsPyfI9tVzLG4zhlIKu9.pNJSgxqjwAuscsTSmMZ2i0a5bKw39oq"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  openTelemetry:
    endpoint: "http://monitoring-stack:4317"
    serviceName: "jenkins"
    observabilityBackends:
    - jaeger:
        name: "jaeger"
    authentication: "noAuthentication"
    exportOtelConfigurationAsEnvironmentVariables: true
    ignoredSteps: "dir,echo,isUnix,pwd,properties"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - file: "/var/jenkins_home/jobs/ecgo.dsl"
  - file: "/var/jenkins_home/jobs/maven.dsl"