jenkins:
  numExecutors: 3
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 3
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: jenkins
          password: "#jbcrypt:$2a$10$6jsPyfI9tVzLG4zhlIKu9.pNJSgxqjwAuscsTSmMZ2i0a5bKw39oq"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - file: "/var/jenkins_home/jobs/ecgo.dsl"
  - file: "/var/jenkins_home/jobs/maven.dsl"