global:
  scrape_interval: 15s
  external_labels:
    monitor: "jenkins"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # - job_name: "jenkins-metrics-exporter"
  #   static_configs:
  #     - targets: ["your-go-app:8080"]
