ARG RACKET_VERSION=8.17

FROM racket:${RACKET_VERSION}

ARG VSCODE_SERVER_VERSION=latest

RUN dnf install -y epel-release \
    && dnf install -y \
    zeromq-devel \
    tar \
    gzip \
    python3.11 \
    python3.11-pip \
    && dnf clean all

RUN python3.11 -m pip install --no-cache-dir ipykernel

RUN raco pkg install --auto iracket \
    && raco iracket install

COPY code_setup.sh /tmp/
RUN chmod +x /tmp/code_setup.sh \
    && /tmp/code_setup.sh ${VSCODE_SERVER_VERSION} \
    && rm /tmp/code_setup.sh

RUN mkdir -p /root/.vscode-server/extensions \
    && curl -L https://marketplace.visualstudio.com/_apis/public/gallery/publishers/evzen-wybitul/vsextensions/magic-racket/latest/vspackage -o magic-racket.vsix \
    && unzip -q magic-racket.vsix "extension/*" \
    && mv extension /root/.vscode-server/extensions/evzen-wybitul.magic-racket \
    && rm magic-racket.vsix

CMD ["/bin/bash"]
