// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Build struct {
	ID              int32              `json:"id"`
	PipelineName    string             `json:"pipeline_name"`
	BuildNumber     int32              `json:"build_number"`
	BuildStartTime  pgtype.Timestamptz `json:"build_start_time"`
	BuildEndTime    pgtype.Timestamptz `json:"build_end_time"`
	Status          string             `json:"status"`
	TotalDuration   float64            `json:"total_duration"`
	StepsSuccessful int32              `json:"steps_successful"`
	StepsFailed     int32              `json:"steps_failed"`
	StepsSkipped    pgtype.Int4        `json:"steps_skipped"`
	LastUpdated     pgtype.Timestamptz `json:"last_updated"`
	ErrorLog        pgtype.Text        `json:"error_log"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BuildQueue struct {
	ID               int32              `json:"id"`
	JobPath          string             `json:"job_path"`
	BuildNumber      int32              `json:"build_number"`
	LastAttemptAt    pgtype.Timestamptz `json:"last_attempt_at"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	CollectionTime   pgtype.Timestamptz `json:"collection_time"`
	CollectionStatus string             `json:"collection_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
